name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  release:
    types: [ published ]

jobs:
  build-linux64:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Get dependencies
        run: go mod download

      - name: Build binary
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/XrayR -trimpath -ldflags "-s -w -buildid="

      - name: Copy release files
        run: |
          cp README.md LICENSE ./build_assets/
          cp release/config/*.json ./build_assets/
          cp release/config/config.yml.example ./build_assets/config.yml
          cp release/config/rulelist ./build_assets/

          declare -a FILES=("geoip geoip geoip" "domain-list-community dlc geosite")
          for i in "${FILES[@]}"; do
            set -- $i
            URL="https://raw.githubusercontent.com/v2fly/$1/release/$2.dat"
            FILE_NAME="$3.dat"
            curl -L "$URL" -o ./build_assets/$FILE_NAME
            HASH_EXPECTED=$(curl -sL "$URL.sha256sum" | awk '{print $1}')
            HASH_ACTUAL=$(sha256sum "./build_assets/$FILE_NAME" | awk '{print $1}')
            [ "$HASH_EXPECTED" = "$HASH_ACTUAL" ] || { echo "Hash mismatch for $FILE_NAME"; exit 1; }
          done

      - name: Create ZIP archive and checksums
        run: |
          cd build_assets
          zip -9vr ../XrayR-linux-amd64.zip .
          cd ..
          for algo in md5 sha1 sha256 sha512; do
            openssl dgst -$algo XrayR-linux-amd64.zip | sed 's/.*= //' > XrayR-linux-amd64.zip.$algo
          done

      - name: Upload to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: XrayR-linux-amd64.zip*
          tag: ${{ github.event.release.tag_name }}
          file_glob: true
          overwrite: true
